// Write a JavaScript program to create an object with keys generated by running the provided function for each key. The object will have the same values as the provided object.

const mapKeys = (obj, fn) =>
  Object.keys(obj).reduce((acc, k) => {
    acc[fn(obj[k], k, obj)] = obj[k];
    return acc;
  }, {});

console.log(mapKeys({ name: "devendra", age: 22 }, (val, key) => key + val));
